### ISSUE TITLE
Both teams same color

### ISSUE THREAD

**Issue by ghost** [byaka/wartts#12]
https://i.imgur.com/yOS1iiD.jpg

https://i.imgur.com/U6ZOJ94.png

**Comment by byaka** [comment]
hmmm...
Can u pls attach `map_obj.json` response?
In Chrome press F12, go to tab Network and u will se alot network requests (if not just reload page and they will shown). Just select any 'http://localhost:8111/map_obj.json' and post here Response's content. Ofc do it when in game and see this bug.

**Comment by ghost** [comment]
Lol I was thinking wtf can I provide with some detail, for a moment I was just going to wget the whole localhost:8111 but I wasn't sure if the problem existed within gaijin or your map. I'll see if I can reproduce as I only tested it on one map due to time constraints. Still can't believe I didn't think of map_obj.json

I'm assuming it might have something to do with the 1.77 update, though I haven't used wartts in a while. 

I'll try it in 20 minutes.


Hey can you point me to exactly where in your github dir is the location where indicators and state are read? I know I can just grep it, but didn't get around to it... I'm looking to play around with adding some more gauges ;)

**Comment by ghost** [comment]
```
[
{"type":"airfield","color":"#1dCCFF","color[]":[29,204,255],"blink":0,"icon":"none","icon_bg":"none","sx":0.673613,"sy":0.641672,"ex":0.655839,"ey":0.637955},
{"type":"airfield","color":"#ff0000","color[]":[255,0,0],"blink":0,"icon":"none","icon_bg":"none","sx":0.343562,"sy":0.670418,"ex":0.361565,"ey":0.672789},
{"type":"aircraft","color":"#1dCCFF","color[]":[29,204,255],"blink":0,"icon":"Player","icon_bg":"none","x":0.611516,"y":0.567729,"dx":-0.690711,"dy":0.723131},
{"type":"defending_point","color":"#1dCCFF","color[]":[29,204,255],"blink":0,"icon":"defending_point","icon_bg":"none","x":0.557797,"y":0.564804},
{"type":"defending_point","color":"#1dCCFF","color[]":[29,204,255],"blink":0,"icon":"defending_point","icon_bg":"none","x":0.609413,"y":0.688571},
{"type":"bombing_point","color":"#ff0000","color[]":[255,0,0],"blink":0,"icon":"bombing_point","icon_bg":"none","x":0.415623,"y":0.687933},
{"type":"defending_point","color":"#1dCCFF","color[]":[29,204,255],"blink":0,"icon":"defending_point","icon_bg":"none","x":0.591868,"y":0.739886},
{"type":"defending_point","color":"#1dCCFF","color[]":[29,204,255],"blink":0,"icon":"defending_point","icon_bg":"none","x":0.602374,"y":0.613349},
{"type":"respawn_base_bomber","color":"#1dCCFF","color[]":[29,204,255],"blink":0,"icon":"respawn_base_bomber","icon_bg":"none","x":0.676045,"y":0.564039,"dx":-266.102997,"dy":138.524002},
{"type":"respawn_base_bomber","color":"#ff0000","color[]":[255,0,0],"blink":0,"icon":"respawn_base_bomber","icon_bg":"none","x":0.347856,"y":0.569349,"dx":271.891998,"dy":126.785004}]
```

**Comment by byaka** [comment]
Fixed, ty for info.

**Comment by byaka** [comment]
> Hey can you point me to exactly where in your github dir is the location where indicators and state are read? I know I can just grep it, but didn't get around to it... I'm looking to play around with adding some more gauges ;)

Sure, check [this](https://github.com/byaka/wartts/blob/master/HowToAddGauge.md).
